name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: 
      - closed

jobs:
  close:
    name: Unpublish Expo release channel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${github.pull_request.base.ref}
      - run: ./ci/unpublish-expo-release-channel.sh ${github.pull_request.head.ref}
